version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Europe/Amsterdam"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Europe/Amsterdam"
